import { BrowserWindow } from "electron";
import { loadSettings } from "../serverSettingsStore";
import { Cookie } from "puppeteer";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
export let cookies: Cookie[] = [];
export const setCookies = (c: Cookie[]) => (cookies = c);
export let mainWindow: BrowserWindow;
export const createWindow = async (): Promise<void> => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 500,
    width: 500,
    resizable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // nodeIntegration: true,
      // contextIsolation: false
    },
    autoHideMenuBar: true,
  });

  // and load the index.html of the app.
  await mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  await loadSettings(mainWindow);
};
